apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel-watchdog
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flannel-watchdog
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, delete]
  - apiGroups: [""]
    resources: [pods/log]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flannel-watchdog
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flannel-watchdog
subjects:
  - kind: ServiceAccount
    name: flannel-watchdog
    namespace: kube-system
