all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root

  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.1.16

    pbs:
      hosts:
        backup:
          ansible_host: 192.168.1.113

    lxcs:
      hosts:
        docker:
          ansible_host: 192.168.1.158
        musicbrainz:
          ansible_host: 192.168.1.197
        fileserver:
          ansible_host: 192.168.1.17
        scrutiny:
          ansible_host: 192.168.1.46
        seedbox:
          ansible_host: 192.168.1.182
        monitoring:
          ansible_host: 192.168.1.44
        ci:
          ansible_host: 192.168.1.18
        mcp:
          ansible_host: 192.168.1.19
        foundry:
          ansible_host: 192.168.1.21

    dns:
      hosts:
        adguard:
          ansible_host: 192.168.7.7
          ansible_user: adguard
          ansible_become: true
          adguard_primary: true
          adguard_tls: true
          certbot_domain: dns.arishaig.site
        dns-secondary:
          ansible_host: 192.168.7.8
          adguard_primary: false
          adguard_tls: true
          certbot_domain: dns2.arishaig.site
        dns-tertiary:
          ansible_host: "66.42.79.175"
          ansible_user: root
          adguard_primary: false
          adguard_tls: true
          certbot_domain: dns3.arishaig.site
          adguard_exporter: true
          local_network: false
          adguard_https_port: 8443
          adguard_self_url: "http://127.0.0.1:3000"

    kubernetes:
      hosts:
        talos:
          ansible_host: 192.168.1.110

    vps:
      hosts:
        vps-proxy:
          ansible_host: "66.42.79.175"
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    docker_hosts:
      hosts:
        docker:
          ansible_host: 192.168.1.158
          compose_dirs:
            - /mnt/app_config
        musicbrainz:
          ansible_host: 192.168.1.197
          compose_dirs:
            - /home/svc_musicbrainz/musicbrainz-docker
        scrutiny:
          ansible_host: 192.168.1.46
          compose_dirs:
            - /opt/scrutiny
        seedbox:
          ansible_host: 192.168.1.182
          compose_dirs:
            - /opt/seedbox
        monitoring:
          ansible_host: 192.168.1.44
          compose_dirs:
            - /opt/monitoring