all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible-on-nest
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root

  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.1.16

    pbs:
      hosts:
        backup:
          ansible_host: 192.168.1.113

    lxcs:
      hosts:
        docker:
          ansible_host: 192.168.1.158
        musicbrainz:
          ansible_host: 192.168.1.197
        fileserver:
          ansible_host: 192.168.1.17
        scrutiny:
          ansible_host: 192.168.1.46
        seedbox:
          ansible_host: 192.168.1.182
        monitoring:
          ansible_host: 192.168.1.44

    dns:
      hosts:
        adguard:
          ansible_host: 192.168.7.7
          ansible_user: adguard
          ansible_become: true
          adguard_primary: true
        dns-secondary:
          ansible_host: 192.168.1.53
          adguard_primary: false

    docker_hosts:
      hosts:
        docker:
          ansible_host: 192.168.1.158
          compose_dirs:
            - /mnt/app_config
        musicbrainz:
          ansible_host: 192.168.1.197
          compose_dirs:
            - /home/svc_musicbrainz/musicbrainz-docker
        scrutiny:
          ansible_host: 192.168.1.46
          compose_dirs:
            - /opt/scrutiny
        seedbox:
          ansible_host: 192.168.1.182
          compose_dirs:
            - /opt/seedbox
        monitoring:
          ansible_host: 192.168.1.44
          compose_dirs:
            - /opt/monitoring