apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.116"
    metallb.io/allow-shared-ip: "metrics"
spec:
  type: LoadBalancer
  selector:
    app: kube-state-metrics
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880
