# ──────────────────────────────────────────────
# PVE Users, Groups, ACLs, and API Tokens
# ──────────────────────────────────────────────

# --- Users ---

resource "proxmox_virtual_environment_user" "prometheus" {
  user_id = "prometheus@pve"
  enabled = true
}

resource "proxmox_virtual_environment_user" "svc_homeassistant" {
  user_id = "svc_homeassistant@pve"
  enabled = true
  groups  = [proxmox_virtual_environment_group.homeassistant.group_id]
}

# Note: root@pam, svc_ansible@pam, svc_proxmox@pam are PAM users
# managed at the OS level, not by Terraform.

# --- Groups ---

resource "proxmox_virtual_environment_group" "homeassistant" {
  group_id = "HomeAssistant"
}

# --- ACLs ---

resource "proxmox_acl" "prometheus_auditor" {
  path      = "/"
  role_id   = "PVEAuditor"
  user_id   = proxmox_virtual_environment_user.prometheus.user_id
  propagate = true
}

resource "proxmox_acl" "homeassistant_auditor" {
  path      = "/"
  role_id   = "PVEAuditor"
  group_id  = proxmox_virtual_environment_group.homeassistant.group_id
  propagate = true
}

# --- API Tokens ---
# Note: The actual token values are generated by PVE and must be
# captured at creation time. These resources manage the token metadata.

resource "proxmox_user_token" "homarr" {
  user_id               = "root@pam"
  token_name            = "Homarr"
  privileges_separation = false
}

resource "proxmox_user_token" "backup" {
  user_id               = "root@pam"
  token_name            = "backup"
  privileges_separation = false
}
