apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      tolerations:
        - operator: Exists
      containers:
        - name: alloy
          image: grafana/alloy:v1.16.3
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/var/lib/alloy/data
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: pod-logs
              mountPath: /var/log/pods
              readOnly: true
            - name: storage
              mountPath: /var/lib/alloy/data
          securityContext:
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: pod-logs
          hostPath:
            path: /var/log/pods
        - name: storage
          emptyDir: {}
