apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.18
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-nvme
            - name: NFS_SERVER
              value: "192.168.1.16"
            - name: NFS_PATH
              value: /rpool/data/k8s-configs
            - name: ENABLE_LEADER_ELECTION
              value: "false"
          volumeMounts:
            - name: nfs-root
              mountPath: /persistentvolumes
      volumes:
        - name: nfs-root
          nfs:
            server: "192.168.1.16"
            path: /rpool/data/k8s-configs
