apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-nvme
provisioner: k8s-sigs.io/nfs-nvme
parameters:
  # subdirectory format: ${namespace}-${pvcName}-${pvName}
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
  onDelete: retain
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
