server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://192.168.1.44:3100/loki/api/v1/push

scrape_configs:
  - job_name: traefik-access
    static_configs:
      - targets: ['localhost']
        labels:
          job: traefik-access
          host: vps-proxy
          __path__: /var/log/traefik/access.log

  - job_name: vps-journal
    journal:
      max_age: 12h
      labels:
        job: vps-journal
        host: vps-proxy
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        target_label: unit
