apiVersion: v1
kind: Secret
metadata:
    name: audiomuse-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9JWuqPtAtpc5Pdr2Xp1Y/ejBmSLRdBI6IFpJ2qDi85hCccv0rETkGRGNnwY=,iv:c2auT6qAHr/sK7+xYRPLm3QcAyXa2srynLhx8yyVTiI=,tag:OADOInjpBKhdbmYergUw6A==,type:str]
    JELLYFIN_USER_ID: ENC[AES256_GCM,data:uGYCJQlRvIqk52fPtcyQ2sUH3xKKzjcb8UT7ByU0RYg=,iv:Ue+8X40mk/NK7TEiiM6SUDv2gZ3Fs16531BWt/SxsMs=,tag:DhJ+PBkQ0BFDLvn10ibp8w==,type:str]
    JELLYFIN_TOKEN: ENC[AES256_GCM,data:dFaAIT3Rcffj6jGdjDXv78FVYnjJsYeyxmYHL71PKNs=,iv:4sq6gqIosrFMffdxN9EUGz9YEIYYkXtghbSjWb4pkg0=,tag:QacmyCxKlKo1O1MaNZPqxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5alJzNWdRekVleHVUTnBZ
            OFhpeFlkOHpDZFZaZTJkVm1qZW5wdDdHMVU4CkFWY2RMQ1FiN2ZNR1JKUE93bkpo
            elRjR2RIMDN2VUlldm5xSEdhekFTTGMKLS0tIHEvTzY2OVdhSGUyd3dCS0FaOXJv
            dzVTb1I3NC9UbndvL0JmbklDOWZHNnMK+Nnp9qWNzkjRCyelKdQxClninWUCgtmv
            t+Xj1erCOPo1BEAxEIfxJewQJkgGpjo1bnK1T6CGG2e+V7AeF78hLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSB0Lytw
            K3pnU0llZDUydXJsNzJ3NnR2dkJYd1F3SE5pRFV2UGVieDhhNnhNCnFtaUM4UlNK
            U09Id0tvdWxvVlVDeUhSUEFHMzJMaC9iai9vdVdQanRxWUEKLS0tIG94cmhYKzlh
            UjU0ODNmbWQ5c0tWTWdzM3RleDcwdnNYNVpJZnEyaXhBUjQKDD8hze832Wr97+Sm
            2M3fwci7YLoNJivbkWhluaDrm2Pn1cFBsDTYSyyTIYrSzcyjej8wvDGLxhDitS/a
            eHkpLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:12Z"
    mac: ENC[AES256_GCM,data:PWPvy9IdOGnJxiDkblGLqua9c9xKUapyv6c5pIQ4v+32HR69n6OaDemk1L8S4tB9EjHARbck4wLqQVO2gfySd46kno8LGFNRzJpWybmg8VNwhQX5eGqydjfwfipYYwjcWkRlOg+nFGQofkYiP/uaoeADQTJA/SXjKoFUjDYqYx0=,iv:dThrOR/XqwA8jCAir1/rfs48zMlEf/+Q7sMoqI/J9II=,tag:CkOHpGLzxZJXpgW+DfXhgQ==,type:str]
    version: 3.13.3
