apiVersion: v1
kind: Secret
metadata:
    name: bazarr-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:DzuGJTLF,iv:o79m4CKamuoOLGy6UR8eBmA3g4ZhbzUCXcBJtUxHic0=,tag:CTqAFxNgfpK/ZGAyyc/HSw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:swo7Wg4wR/PL0XAR9kIjk9ME+Jw2OuQQMAgLSOdNbKrpbsWbZpWpk9IUX7tpgLBg,iv:NTfu+9sCF+sbw23FD1rJEDTjVMKMoJU0H2In6tENIhY=,tag:NwzEB8MWZ1TXzhhokh+6zQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMUN1TmptclhrUXhMZ2tE
            bjJKekJRUkN5ckQ2NlhBVFVqcWhodHFUaHlNCjlyY2xBM2YxdjBRQkxDVytwNUd3
            NVlXUkJUdjNwZnhrbTF6dXpXYkRjdE0KLS0tIFMvczhlSml1SmF2bnVwU29pWlVV
            cFBVMWR4VGl2NnRBd081c2k1YnBNdDgKR0dojhQYd41iBOhgSO5x0sfbmfvTaUD/
            AYsddCQn5mxvta1sNF1puiquRugcjwaTVZYEPa9jFKzqWi1UGEWt8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSBYUHJI
            dnFKVlRTVUlGN2c3LzYxNmZsQ2srcnp0eU0zcGNPVDMxcm55QXlzCmxqTWFWWkxv
            Z21JRVBvVEkxZmdkWmJQYnowZmNUWHZhbG4vL0hwb3pJekkKLS0tIGVoWVZyeDZh
            ZmV6akpjWm9tZGduUWFqYUdJSFc4cGF3Ym5sQ2E1cmpCR1kK56f88IfiFfeKiYkR
            X9vvsOcUkSsYIoccVrVb3Tgyr32pVikJFWg9sxrHPIxo13CD+/U7Qissxv6FfHIx
            sIY/LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:MnaBjOrQIyRwDEHnHfquZKaPNF6/aAMXTDVDgP/0N6rCeOUNZ4pm/HdMIpnvLfPRLS6WYOjOiucQ9VFAuGvmTb/FMUy9H30GmLNa6bF1bmdjMCIg6Z2xTopN+B6xAfcSJ1fl25dIDYLiQvBX/49ex3gViiQa3AhiNYJGyBvJl5s=,iv:KHo1T8LBsL1yIrXg6jScD6QaSuBLvYk0/nsUX7ZNdmI=,tag:LipJiQ9Av8m9HQWAMbU4hQ==,type:str]
    version: 3.13.3
