apiVersion: v1
kind: Service
metadata:
  name: copyparty
  namespace: media
spec:
  type: NodePort
  selector:
    app: copyparty
  ports:
    - port: 3923
      targetPort: 3923
      nodePort: 30806
