apiVersion: v1
kind: Secret
metadata:
    name: digarr-secret
    namespace: media
type: Opaque
stringData:
    DIGARR_ENCRYPTION_KEY: ENC[AES256_GCM,data:uhbrlFP2Ij9mMT5TsR9EI2/vKij4C0bia3+HAdm85Y9mda0Ov9c259VLcEI=,iv:KaEQwNFeCZ9ij1DtdBH5hfTutrj2gYD/D5r9+3bdacU=,tag:C3GVYz2giSoTAr7XG0I47Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN20zNFdIcTN5WnlSRVZ5
            YWtwckVjM0twdjhIM01GeUlWNWREUys4UVNJCloydGtVTkNjMVo4WHVidGt0M0to
            ZmV0ZkxaZGtmNGRZMHhmb2xaSzYxZWsKLS0tIHpSMWFGTVhUS3hIUTYxUHo4YUNp
            ZURQWk1ZdlF1TDk0S3ZLOGU0TFlKZGMK5O5v7OAQHRih/Jss6pJBSGCdbehoXbti
            CjmxY2Xqx0iK0xU5bIiWoQNraeCmBAT0o6ra2e6H8zXozDFf1fw5+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSA1SHZX
            VWVybEFLK1pWcDltVWVxUXBOMTdteG5IeEh6RFV0N3lHS3ZiaFFNCldGMEdFelR5
            Nk9IajEwbkc3YkJwbXZ3WkoyL0YyWnBsVzJlSFZ6TDYxWGMKLS0tIHMzRy9GTWh6
            VFpGejg1RnphVWlHbWQvb1ZjUUxjUVlsUml5MUZLWUlvMWMKaCPP2+JveGde9WxS
            9t7GM8rWVTOtTGxmcPupon8dagvpSQnUnbAxkPIsbSt3UjjI7f3sM5tmJyj51VU8
            0xbHug==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:12Z"
    mac: ENC[AES256_GCM,data:aYIdkRCsnQI1IsF/XtjdiQfRNdvJISrW4ByJqK9ZZjeAEWTNkvDqiCRbYIhWBNcuWDyTDJJW/yZHAX5on26LYFOR0TKupAlkKi8QW6IQ47fzoMqxXEWr9skjNKXsRRH8fLzwUsvamBKBwHXlWG+BTOFUQdUnwz0XEW45dgWBGDQ=,iv:M/rPkmjPlRHNRNqnS8U66+G/SzZisk1kRRjNBzh+8zE=,tag:7kx5W0BwJY8m/+CYHEF/Cw==,type:str]
    version: 3.13.3
