apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.4.5
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "dash.arishaig.site,localhost:3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: media
              mountPath: /mnt/media_root
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-config
        - name: media
          persistentVolumeClaim:
            claimName: media-nfs
