apiVersion: v1
kind: Service
metadata:
  name: jellyfin-pgsql
  namespace: media
spec:
  type: NodePort
  selector:
    app: jellyfin-pgsql
  ports:
    - port: 8096
      targetPort: 8096
      nodePort: 30814
