apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:t3PKgyi8cFU=,iv:zQhamsakyDqUwDoaEp0B6QZI2HY8rHELSmHbD5IoOSM=,tag:Id7QYr/RKh4t0FOmi9XBNg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KO4e7SWaB70LzbHYq5ktDuwQrgxWHchlE2/AzfigLJ3qbkiJ18CvE9Tygg0KYNZA,iv:a3LR15ljTfm7Vj6gBuf6SoZy4VHRFShAQ2TTMty6KXs=,tag:mHnbd68SrejBq4yw+7gdyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMnJDRHpxUklITUxma3FT
            NlJjajV5ak9JMUM2VnhRaTRPSGMwV3FVd0g0CkdJOFhUa3l3alp1WUJWYVlxZmFZ
            ZUlYc2pxYzJzVTBjbGlIS0gvWmY3emMKLS0tIHczNytrb05pL0xGNXdNZE41dEdZ
            UWlVWFE0dWc2RjhNMnB6dTE1bmttcE0KI3ry4rFhO/y8LufgSfpP9N1sA7aqm59M
            d58fEhc3Xd5qhln7K5VBaVc3WqXjV0ivLeWcw+1pwZXo59ouiBAiNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSB6bkFP
            S0JBT0RqL2RmV3VnVDBwckpUaGFDZVhDMVMxT0cxTk1VWVZiK25VCjIyNWVLRmZh
            RXNaRlh0MGRQOERaUlQ3aklmMWRCNnZXK2Z3NjZFOUhwWWsKLS0tIFV0U0RrUDdu
            bUkrVWN5NTkvTExnaWU1Y1NmMitxeXVVcDR6K21wK0t1ME0KzTgAtTELxqyLZW2T
            wPlbvLcJHhDcdlxBPMoNFr2AZxfaeUUI9Alw5O0QdTa6fBQIf98txTOdsFXMp/KS
            MlYSCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:MpYB5jxkhMB5y/Mj3xwTzVbh+a97AfPHlDSg7I0r3BctG9mZQhQ5GOLEym9jZVziHMSpPnJ0UTJ8eWJbjxkWEOXtf1Txe7gLmmyYwUY1sBFg1UOyrHd/FBj+i7ZixkKbO64vjAbUWe3+EmATy86px2g9Qcu8y5P905Brni0EH0I=,iv:M7paqxD2toTQoOlF2Wys67FS0YveubFe1dTaBVo6SS4=,tag:LI5sV/rvZo5jxSByIH+gIw==,type:str]
    version: 3.13.3
