apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - media-nfs-pv.yaml
  - media-nfs-pvc.yaml
  - lidarr-config-pvc.yaml
  - lidarr-deployment.yaml
  - lidarr-service.yaml
  - bazarr-config-pvc.yaml
  - bazarr-deployment.yaml
  - bazarr-service.yaml
  - subgen-models-pvc.yaml
  - subgen-deployment.yaml
  - subgen-service.yaml
  - prowlarr-config-pvc.yaml
  - prowlarr-deployment.yaml
  - prowlarr-service.yaml
  - sonarr-config-pvc.yaml
  - sonarr-deployment.yaml
  - sonarr-service.yaml
  - radarr-config-pvc.yaml
  - radarr-deployment.yaml
  - radarr-service.yaml
