apiVersion: v1
kind: Secret
metadata:
    name: lidarr-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:KssAczIP,iv:dZ/OxzNXaL1hV/Hxr+EjR+BGgD+xTxZI8KtzENP5mow=,tag:6dtvtAHcYg2LXSjwRZ9SZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8+6ZbhSwLBvZLj5U9xv+hKMO0UMWwaC0AB+kWVlDGRQ4vUcg2qc5w+ZiyGLaarjA,iv:DM6e6lsgnWRTIMIxw3wEM+2WbnwlhcywUWDHPYEbsgY=,tag:GIfCsZvP3rBUHMQgN99KIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa29wcndEMERHeGhlOWth
            SkZsSnF4eG55bnI4ZFdSb2lpUFNQNUNmeVJvClMrRyt2c2pHVWl0N251K0F1NEk1
            SGZPakFNTzlQNGg5dnpodnNNQjZqSzgKLS0tIEEyb2VzM3RkS3FnTDJrTUQwM3Np
            RTUvMzljb0UxSGNFb3o2bUhDODdrYmcKc+SysEsKR3MNzzZfc7m0ieBmDvmmHoh+
            ZZOhhqTEp+pcUKkrha/l8Nvzz72/d557wVbhlIULrDIyJattoa6L4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSBvV25o
            cU0vcG1hWGxsTGdsRW83YVFiYjJwemxWZThBOXFDMFlwdE0zQ3pZCml6UVlzRTZl
            d1N6Kzl3RmRaOFRtM2gvQ1V3U2lQcjkvb24wZ2VEeWhodXcKLS0tIGxKLys2QTQz
            dTQwSzB2OGdrMG9hVjRKZEFQVTVYeTQwcGNLVFdVQ3dlb0kKylhlNFS61wyvoVTE
            6d3rmQM6ZSQSZE0iLjX9IWaaCQWr38l41gRTIMzM5jNAiAiXR5v0UhXyMjn4kpsZ
            2vyf6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:ry9aP1SUP/Tcg/DYpFaYxoKgdstQWbDv9P8ZtRxdnuj5gDvCdzDKJHXSg6DsajSZY8DBufjkIiZQ0pbuPw8LIcgyXKzCsoVRxjWZPMewzal8C98VrjCmxGxg4blLQC7y3TBLNLuW1qogAijP7LIEz1UCRQVd0IboBnI1miN5omA=,iv:O7XIZXet6ZwqCIw4DaJeHJy917b3cwFV3fDmZ637fuY=,tag:b9BevkoVAXo/ipfRssvH5Q==,type:str]
    version: 3.13.3
