apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  selector:
    app: lidarr
  ports:
    - name: http
      port: 8686
      targetPort: 8686
      nodePort: 30686
    - name: metrics
      port: 9709
      targetPort: 9709
      nodePort: 30709
  type: NodePort
