apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.19.2
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: ALLOW_SIGNUP
              value: "false"
            - name: BASE_URL
              value: "https://mealie.arishaig.site"
            - name: DB_ENGINE
              value: "postgres"
            - name: OIDC_AUTH_ENABLED
              value: "true"
            - name: OIDC_SIGNUP_ENABLED
              value: "true"
            - name: OIDC_CONFIGURATION_URL
              value: "https://auth.arishaig.site/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              value: "mealie"
            - name: OIDC_PROVIDER_NAME
              value: "Authelia"
            - name: OIDC_AUTO_REDIRECT
              value: "false"
            - name: OIDC_SIGNING_ALGORITHM
              value: "RS256"
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mealie-secret
                  key: OIDC_CLIENT_SECRET
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_SERVER
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "mealie"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /app/data
          livenessProbe:
            httpGet:
              path: /api/app/about
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/app/about
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie-data
