apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medialyze-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-nvme
  resources:
    requests:
      storage: 512Mi
