apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metube
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: metube
          image: ghcr.io/alexta69/metube:latest
          env:
            - name: DOWNLOAD_DIR
              value: "/downloads"
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: media
              mountPath: /downloads
              subPath: downloads/metube
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-nfs
