apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omni-media-server
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      omni-media-server:
        strategy: Recreate
        containers:
          app:
            image:
              repository: nginx
              tag: "1.27-alpine"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
    service:
      app:
        controller: omni-media-server
        type: NodePort
        ports:
          http:
            port: 8080
            targetPort: 8080
            nodePort: 30817
    persistence:
      config:
        type: configMap
        name: omni-media-server-config
        advancedMounts:
          omni-media-server:
            app:
              - path: /etc/nginx/nginx.conf
                subPath: nginx.conf
                readOnly: true
      media:
        existingClaim: media-nfs
        advancedMounts:
          omni-media-server:
            app:
              - path: /media
                readOnly: true
      installer:
        type: configMap
        name: omni-media-server-installer-config
        advancedMounts:
          omni-media-server:
            app:
              - path: /installer
                readOnly: true
