apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:i+Bl8GkQ,iv:fyieRDwPcP4QGnsOgPUeHozON/DgjPRxCtjkJ0kHkEU=,tag:ovFL7Tsjq0iajFeWUmPl+g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:P945pEyz,iv:WH17icB5QQ58A2WRwYQb0+PTv2CayG/DIKev8XfwcY8=,tag:Sc0DIQ7WNIBcd+V5Dwuvng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y1NrUDRUeDBQcWtFZjNP
            ajI3Z1pUNzkra3V6cWp5VExoYytva3U1OGtzCkoycGI0bytldCtVNVphWUhwMUcx
            TVR4dEpVbnUyTVJNZGJqaW1vTnVoeG8KLS0tIHdWc2xDOUVvbjNYeGREQjdFWGtL
            Sk1BWm5qQXNFSkU3eC94RW10SEd6cmMKXnuE96ytfbyWGd1oUSAnKp1Qk9ZckrIV
            hC1J7eKpzeihLud2hA+lZ1Ru+m1SggLlsHxzrrZW313B4l9X9KlzYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSB6aDJO
            SEV6c09qZmovY0NaVnpFUmliWXZTMDQzbmZCMDR2YThVYUM4SWpzCjdwSGxZVTZ0
            UFluYXNVbnh5QXdsMk42WXdTcUc2N2lIWmo1WWVtWGVKcmsKLS0tIHFBcnFoTlNQ
            NWlRdmR2U2R2M0dkaGh3RllGV2tTSnRlQVYxd2Q5NWVReTQKzdPmTGbzQjkU0E0u
            VIo+LZeHu0KZzu3VKeJ03l0V8UxOkxnvewTljiGPO1XbNwtiFOdK24EuYUyB+rYG
            9I5kZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:jmMBBR2xtGKVj0In/4tQUod77HGys8RPqvYCjy+ceGV3zuzA43mDATVoPAKGhWKl00vLtiBqR1dWEz6oSbcpFxBbrKnhiTOLsQ93D0AdKRavdQfkM1amvxEdRM5zKn6ULoHlNH+c3UMJpstIOgKCqtCF6pUsTnFNq6z4wQpdW3g=,iv:duiBIsuFCVldFI53akj6arAd5hTtuXd0a/UlU125HVc=,tag:jh3YGREQr9fBpX+dR3jnWQ==,type:str]
    version: 3.13.3
