apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:F99LO+IMw7A=,iv:rUW9393BWmt7l2N31B4x5/8+q2FSKzKgY1pElqPvgYA=,tag:wRJW+EXsIhDXeCD0BhdMmw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KgjXqjE6fdpJQnOQgXqal+OlFKiKGv5Hn3B+j7NH/r21tzB5FkmX/ctZHli6RsWv,iv:AVQnP76Cv3A3hJrVgBqJ8l1CEIvVJiSr19BuUUIWILI=,tag:wT58siCm76vYYFICtoNxoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVTBEZFZQcTlxME9CYkUz
            bWF1b1p6QSt6Q0lQQis0d1lwQlE0MUVXalJvCk44d2dONFpSYVlOOFAwbHozVDRx
            THlPM2hDSXlNZ09pTTlMU2kzRDlVSlEKLS0tIDlSRzIxM1UvM29ieXdDaE0yRHh5
            Z21vQXZvVjdJWUhkQzFmRWhEZjRtL28KHvmJZV8Df1kEMtAOSPPNENutuAwcrmRq
            A9z4f1/j5Qy8D1D2RXsbgC+qmcd/kSQKaRmnseoQIDmrDIF2NFZcTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSBmSDVB
            WDdRT01oakpGQ3Y1czh6ZFRmOVZBdWIvNmxYL3BJa3dBeTFSS2t3CkU3QUpGVWpa
            TzBrem9JQXdpR3duK2MzM2NwcnIrMHg4ei9sTzcxdlNqdzAKLS0tIDRaVGh4MS9m
            RnIrckQwZ3Z4am4vNjlXY1pSdGlzQWhvNFN4UUFQN3RSTjAKl2F/0239WYvWzsG9
            DilbnwacMsXaKZDNIMZvliLgVOZnqYIcG8jhxQ52Zo1Mr4Ciy62xfAxS/z9OT5VC
            6O5iVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:W5vkWG0LkWhZiDtmvMXRRT363a4OEjgpZhcbAXS2NMSvEPz2HpdLDkqG9aWY9nGkjdhsg7wDmau5mI1Le3D3Fj9WzufegUTbyiReH/i+LI02veDkr5TUKGqYsHiQrtDFt1exQo2A52OG49a5IpiJnBQGFPkika0+2V9/gu2nGNk=,iv:0YGf4hUl6g5fqe4JlKOpasshIXGbRlZJLGUfL8KR0tA=,tag:PYdKARwtah5UTE6/bpKJgg==,type:str]
    version: 3.13.3
