apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      port: 9696
      targetPort: 9696
      nodePort: 30696
    - name: metrics
      port: 9710
      targetPort: 9710
      nodePort: 30710
  type: NodePort
