apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.116"
    metallb.io/allow-shared-ip: "metrics"
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      port: 9696
      targetPort: 9696
      nodePort: 30696
    - name: metrics
      port: 9710
      targetPort: 9710
      nodePort: 30710
  type: LoadBalancer
