apiVersion: v1
kind: Secret
metadata:
    name: radarr-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:rJQl5f2a,iv:7BwMurjwU1gsTxoI8JbcgByIxMv4h8OGEX1p4duNfQ8=,tag:w7QAsjDopLSGwmGd1k1E5Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:60Cw/N3ufB1CgbBNAOrJ+AmoIHaODvp+oXh3hzbxlyqAB9Yx/LjPGOg5hh2THVB2,iv:aMIy9k+dJmoJdQtssXRzRLmI4+y4B1w/a1r2SDtRhyg=,tag:xHXDEE/PcDGg0XbLXsoICw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFZqak81cHFrd3hBQWYw
            M2NmVXJtMnhNc2w4blRpL0V0WVNuZVA1eWdFCnkrNS9JdGhlbEpGMmN3WG50dDdm
            c1ZJN1p1UEl5UkNPakcwdDZYSW5NNTAKLS0tIFZXWU9MV1F6bmlXVWlSdjA4c3pM
            bFpoalBkM0tpeGlNVnlBaDJpYjlDNGcKyHHlcp2G6EgJaxqDAHvFZ5YhnMlQOmvg
            SqNXXtRpMI2L9TfFVSwCinVgyyJjP1gayFJwfWyH4k1Vo2JT98FW3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSBDVUJU
            eHdISkNZcXFNQW5ORWdPWjNwN3YrMWVvcCt1NTdDT2JuOGlBT3hzCmZMcFVNZ1ZJ
            WXVqYk1EZ3phdVcyb0tqaEhuc3VUeGVtYUxOb01KQmk5NDgKLS0tIFhJNXBlUzBI
            c3JIS25HOUV5NVZMUFRDaGk1bE93UEJGTU1Pelh5TjBsaHcK2xi+VbCBzy1k0RFO
            QBIKP/bK36bMAhC4zVmyhnmEjetI9gYSvFf/PNUdyfvE24HH12c4/4FIRzI23i2T
            KUjZVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:VYkDPEmwecCIFN8m8BpMpTes+xrOgV9fgjFaR4JOYavxhv8o5USBuZ16OUFM7L/duehfLBTI0l/KWKUj5NuMpBf9n0feravvjNXRUPR4X8ixBsxEzcHKU1g0O9PrZNh8v8hug9HZ6KAD5KUbkNysfWxWFfpg6M6xg/70xPMTlQE=,iv:nkxZs7QzdaMYjTbZD8tFW6TbJEi7HXXmBrjIjXAmyhA=,tag:syqUS/aizEONB7RmVBA4mw==,type:str]
    version: 3.13.3
