apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-nvme
  resources:
    requests:
      storage: 1Gi
