apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          restartPolicy: OnFailure
          containers:
            - name: recyclarr
              image: ghcr.io/recyclarr/recyclarr:7.3.0
              args: ["sync"]
              env:
                - name: TZ
                  value: "America/Los_Angeles"
              volumeMounts:
                - name: config
                  mountPath: /config
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  memory: 256Mi
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: recyclarr-config
