apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: media
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      seerr:
        strategy: Recreate
        containers:
          app:
            image:
              # renovate: datasource=docker depName=ghcr.io/seerr-team/seerr
              repository: ghcr.io/seerr-team/seerr
              tag: v3.3.0
            env:
              TZ: America/Los_Angeles
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/settings/public
                    port: 5055
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/settings/public
                    port: 5055
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: seerr
        type: NodePort
        ports:
          http:
            port: 5055
            targetPort: 5055
            nodePort: 30801
    persistence:
      config:
        existingClaim: seerr-config
        advancedMounts:
          seerr:
            app:
              - path: /app/config
