apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:n3bZUBs=,iv:/EYI6h+yzxaIQeIFSS3PoPr+gagFGmTo7Lx7vL1CcHw=,tag:XNPjMCWGKUPuovzIjXSKcQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Lj+l6gyTNLVKAG6RDSu6zDHlgO2ZNVCBSPd+xEJZRuZs0SMTQ0/2VkHjeNL2skQT,iv:JrdDGnfeBVQUaedaGZekRGNF0jjunaX4XBCaVF2ozX0=,tag:EONcj61ihpWG929VczsztQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFRHNkhpTVdjN2hmWm9O
            QjF2L0VlL09LKzV0N0hiU3JXV21ralFGTG5ZCjY5eVJWMjlCWmhjK3QwYjJHbkRL
            dzhKUVQ5U1Zycnc2MzAwMXNOL1pzZWsKLS0tIDFweTVKTlJTUmNQK3FEYmFCNzhx
            bHpnOHFCd3kreVBsSUQ4dXU2T3B3UTgKv7nn7AjybvngVLLV9WRAPk9DbyhsWgSX
            CY6hLkpUyaR/m34KvmQU+7ZVZP56WD/Vsu1B+DObe0/UkOg/MDMtBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSBHRjBH
            TU14TWlmNU5ZZEhnMlNxTmNmbkpJUUZiOXdCQXViUUlkbkFNRW1jCnpnZE1HVkRZ
            UVh2ZWlPcHRTSDJ3VXoxTmdzM0NvU0FZKzdiL3hNWFl4Mk0KLS0tIE9wbjc4UGZE
            SUN1SElsOVFQVHdOSndkc042NXlEdVZkUU15ellIUk5RVHMKXpeJkoZKiG1TtzDS
            EFPpWy1FHeZhUxHDP5IG0vix6GXcjQ0WUYNk22edqDFMHB0EPGE+lSaNqGvrdoSN
            RKKG8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:+qmGpvQgiP3790zXMvsFm8cfF0VjSjOCxrHmONsYKp46+1u1n1qHEmZTqWBlROK8cdgoa5g2cUAhhod8XoD4O+J1YOkp4fi1qWAwZIYYUYCv4DWbXMkEyC8rRBnOUAJDvIBkCL9ywUDoNE8evavBALBmfC6CXyuAemf+dNseZa4=,iv:2k0Bz/btOCEvUbahuDfEYEG5GlECXL6XeCTGUTwoQC4=,tag:lV+WH6j+l/AFt2o0eceSFQ==,type:str]
    version: 3.13.3
