apiVersion: v1
kind: Secret
metadata:
    name: sonarr-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:eeS9URwK,iv:RlIrBJkaLtoAMRkeRnOTovDwPo+sBTvHOgBUdT52Azs=,tag:t/Qcxe7xYhp1I3y7NjbqDA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jrs3/7tJHNokOGnKq1pQToHPEQ7T/hrqRpoQ5ydcmn8OBK2BZDqXSUsQ0oYF2pQ/,iv:4BI3qKUGtYdmlWMJpVzzDN1opQx8RysdicaVsXa97tU=,tag:+bFYTIR5HzjX+NRPO3hpIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVHMwTjVjMzJtblk4N2dK
            eWM1bVBwbTB4dE5XWTVLUGdSaXNqVHd4MTEwCjhqallWSlMrZDluOWlFUHNIS21T
            dWlJMFVlNjhleVlZNDJrbFdBN2hYeTAKLS0tIDdWOHBCd1FzUW9MakpkbWhJQ2VQ
            WCtpNGNaeEFLTjZWemNQc3NoL3UwT28KAe9jqIRVni7OHqPaqc1F7c+lxdJ49nlb
            Z2W+Tlq+VGCGsRlUSdXXshN1U//RjHLiHanEbcXACxWxKNxeF4w0gA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSBDM3dG
            WkF5Ty9QNW1kbldONlRScFRiZ1NwNEEvQ3N2RnJnNmVnbTl5NG4wCmpsSmVFaUd6
            WmNzRGY0ZFVYc2U0bHRxMmpTT3JiT2Zsb1VvbmVndW8vbHcKLS0tIDN5b3pZeEMr
            WXBCUFo3Y2ZacnhZUk1zM2JaUVRLT3ZwLzNrQjAyNjRoK1EKU2bSljuk2SfcA2q5
            Zq5SkFzvN4FRor2X7JPFnSkn+jIRRV81zyNUtvzA+w8hJhSd0QFDxPDqqxeocLN0
            Oe70mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:11Z"
    mac: ENC[AES256_GCM,data:DxeXWwrpxVtAYxV2ha9oXGVlkPw8SeyAes0eVmPni1cOO67rqIpqk9aOQG0HkzkT86nRoBldnwMMEMzZXVPSowypDs9OQ3lDvZpZ4DPf2/JABdeBxREO0jjMHaSVZdfVlPXNU/tQjPPTF45NQWGkhvd2Y2KDHmqTbP3gGTtmZ+E=,iv:4xIvCz/b37qbaYwQ4gm7LUzwxMOJCCFfcgLYCgLogB4=,tag:tspe7dux8pXef1+9/nEQCw==,type:str]
    version: 3.13.3
