apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.116"
    metallb.io/allow-shared-ip: "metrics"
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      targetPort: 8989
      nodePort: 30989
    - name: metrics
      port: 9707
      targetPort: 9707
      nodePort: 30707
  type: LoadBalancer
