apiVersion: v1
kind: Service
metadata:
  name: storyteller
  namespace: media
spec:
  type: NodePort
  selector:
    app: storyteller
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30810
