apiVersion: v1
kind: Secret
metadata:
    name: subgen-secrets
    namespace: media
type: Opaque
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:AZlDPrbu6hPWUbuIhcRobWhyewD3nxUkmza0QK0lvebpJAGpMw==,iv:uovN6Ex976hTV8OisncluYUwG6lfXZX9ksMkJVxP+wM=,tag:LCjmUX75pgQvLOwXEepZSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YU9JdUkydXNieUY4MXEy
            aWZrdHFPc05DRFBGSGRYSzNnK09DZGtYQzJRCkZVTFJrTjNVQWtUMEdmWnVxT3pD
            Ny92NXFzTUlmZXJ6RWNRUGVXL1JzL3cKLS0tIGIvSTFEcC81OVZmclNabW9wV3NS
            a2k2SlF4NWg0Y1hkR2xoQ0g2eGhhNFUKLLtJf0X75OXg4k1qyqw1kBxd5M1ip3Pf
            owH4qzMuaJzJnW9hmpeqVTBtM/DYoZa2PcAPwTdMthFnMn/2Md8vyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSBRVXRr
            bGpuMzlkQ0ZxeHpDZ0Fvd21lZzhFL2dRdnlPRUZ2UFhrb3BhK2dvClEyb2E2Tjl6
            NmxsbXR1dnBidlNrVmoyMzJPSkg1NkRNUE5pVFhpNnFTWkkKLS0tIHFmN2JEMytk
            VDBLaUQ5NTkzSC9QNVo3NjdSRWk2d0R3RTVNQnNMSmhYS28KydPSLI9BAj7klh1E
            TXmmz1EiIn2ZgBHhYyo+UF64muB/b2sf1bDLH/seMzmfTekK0R4uoomr+4qvhi79
            LHRkQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:12:12Z"
    mac: ENC[AES256_GCM,data:Agdn0xST5EE0QGNM0kJDYq//6qrUbyB7q8oxj9y31ohY3swNMKbVbNv17rKSOGF4itLsxuq+Ofn/8/W4EuSbBkReiKcJkjj48x4C4UZXxiHJCwp+ltkuyjH/NmNZS9NfITan7McX/RsuAvKaXUhfaOy25ZMopnouHtYL4oAAL94=,iv:AD3u8g6B5OTWPmtc1CsxPw4qsLO3kxiDGHGf23bjSkY=,tag:lm/Igl9fzNWXjwiec78SSg==,type:str]
    version: 3.13.3
