apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr-node
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdarr-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tdarr-node
    spec:
      containers:
        - name: tdarr-node
          image: ghcr.io/haveagitgat/tdarr_node:2.50.02
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: serverIP
              value: "tdarr"
            - name: serverPort
              value: "8266"
            - name: inContainer
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /app/configs
              subPath: configs
            - name: data
              mountPath: /app/logs
              subPath: logs
            - name: media
              mountPath: /media
              readOnly: true
            - name: transcode-cache
              mountPath: /temp
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              memory: 4Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tdarr-data
        - name: media
          persistentVolumeClaim:
            claimName: media-nfs
        - name: transcode-cache
          emptyDir: {}
