apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tunarr
    spec:
      containers:
        - name: tunarr
          image: chrisbenincasa/tunarr:1.3.5
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: TUNARR_DATABASE_PATH
              value: "/config/tunarr"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /config/tunarr
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tunarr-config
