apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcharr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcharr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: watcharr
    spec:
      containers:
        - name: watcharr
          image: ghcr.io/sbondco/watcharr:v3.0.1
          ports:
            - containerPort: 3080
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: watcharr-data
