apiVersion: v1
kind: Service
metadata:
  name: watchback
  namespace: media
spec:
  type: NodePort
  selector:
    app: watchback
  ports:
    - port: 8484
      targetPort: 8484
      nodePort: 30804
