apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/
  - local-path-provisioner/
  - nfs-provisioner/
  - cert-manager/
  - metallb/
  - traefik/
  - authelia/
  - alloy/
  - kube-state-metrics/
  - rpi5-net-tuning/
