apiVersion: v1
kind: Service
metadata:
  name: authelia-metrics
  namespace: authelia
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.116"
    metallb.io/allow-shared-ip: "metrics"
spec:
  type: LoadBalancer
  selector:
    app: authelia
  ports:
    - port: 9959
      targetPort: 9959
      nodePort: 30959
