apiVersion: v1
kind: Secret
metadata:
    name: authelia-env-secret
    namespace: authelia
type: Opaque
stringData:
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:XwOXAbtm3v1/rid+7A5MmAdG6OwYvCMfwsLTEu/XFVqZEZz6Yh/jAnQEvjb0w6RJrcxE5Whz8iVZu1JzGu/KyQ==,iv:MuQcKSHq/3jBEq7gW7+2WGZcjhQV3zlCQb9CJ8FPhm4=,tag:X6uQizQLjtbu9Mf887juKQ==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:nFOnqUoycoAJMaoR4AaBlDND85c0xg+0VjBgCHYsJwLjWLJKueyr/Jeb7nPU2+3SVvz+DjzOoagEJfn6i+CfSQ==,iv:9EM7V26V+slsefiQL4P7PqA3z2DuNiXBqUrCxCoc/RY=,tag:QAzPhRLUZTROV56r1LIVTQ==,type:str]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:2LM6XoRdq1umDdfm74FM2ckkwcLhQrgGLvGLXqwdBa53w/I+WCMpbWJdU6LCs5czXwExKUvtMKAT5SmQR+tL1w==,iv:ufKogiAfm1psiulTc2xczwKthqgFOm6uxJxo+Gp3tiw=,tag:YYJSF9nxR0QmoofzGO+cIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MTYrQUh2eTV0T1pGQWZx
            ZzZrRzlqdUI4amJ2MllBTTZvS1hTa3NiNlRZCnFwRWJ6dUdGNUJLRTVxbjhSamV2
            RlAwZm1RcS9hcmIwOE1sVUV6aGFPRUEKLS0tIHpwUkhRd3R0Rk9TUDRLcFpvaXZq
            RUpWTW12aVU0WWNxeWxlZ29RWXVrbVEKqK5mA+LDz22XoIQ299sOz0LKQjva8mVg
            9hXBsDj+Sj4sPYuboBoubDpYohxjYjOvTYyXdrS5+w6gRDMB8s+PQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17pgmpmdrwrdxtw3rxlyumtcl78nwv4d3errll2u687uvhkxmzg4qefuw95
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFByN0NRUSAzR09Z
            ZW9xYitxSTNUcFJCT1V6dStNeVRzV0sxTng5TlBiRXZxS204RHkwCkV4WW5WUWVT
            WW5CV1FCaDlmN1p6V0t0c3dIb3NmS09wTk5xOVFPdUFtT2sKLS0tIGdNcmZmQ21j
            cFJISjhDdG51b0llQVRMUFJjdzFmVHN2d2RzMDl4UmRLUzAKFhXqS1juEm8Boimq
            pKtTQ0LI2IkIeZA28TR/S83Qcw94doYMxUJ5mHTqHdQngsfJX+kSEFmrAqKIBq6N
            YPObaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPpbfa/Dw9jY/uvl6k549/LREsabJ21/rM52NGuofFCN
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T05:35:59Z"
    mac: ENC[AES256_GCM,data:Rl1rR2oraTr/8N1QSxR5t5YdUxpK9WfbcHyEdTV7SHVCYAVxUEgA3i0rH4kM13s2CdAfT2S4oTiKxg/YG+ORakQysAg0Mj6Fh95XFiZDF+FGOxoi7V8dOwi/QlC+b+gLpz4J+3W3WMgu+3rEph9BBuDnxA+0ntPe8vRT7Ng6SBs=,iv:QCdwAbQtGznC3lh50UNyBFBEEPtwjzGsAAU/gbbqNb8=,tag:4nrarGRHZ0limatA/vlZQA==,type:str]
    version: 3.13.3
