apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: authelia
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.85.0
          env:
            - name: REDIS_ADDR
              value: "redis://redis.authelia.svc.cluster.local:6379"
          ports:
            - containerPort: 9121
          livenessProbe:
            tcpSocket:
              port: 9121
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9121
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
