#!/usr/bin/env bash
# gen-mcp-secrets.sh — Generate ~/.config/nest-mcp/secrets.env from the ansible vault.
#
# All credentials live in the vault. Run pull-secrets.sh first to ensure
# the vault is up to date, then run this script.
#
# Vault password (in order of precedence):
#   ANSIBLE_VAULT_PASSWORD_FILE  — env var pointing to password file
#   ~/.config/ansible-on-nest/vault-pass  — default location
#
# Usage:
#   ./scripts/gen-mcp-secrets.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
VAULT_FILE="$REPO_DIR/inventory/group_vars/all/vault.yml"
SECRETS_FILE="${HOME}/.config/nest-mcp/secrets.env"
VAULT_PASS_FILE="${ANSIBLE_VAULT_PASSWORD_FILE:-$HOME/.config/ansible-on-nest/vault-pass}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
fail()  { echo -e "${RED}[-]${NC} $*" >&2; exit 1; }

for cmd in ansible-vault yq; do
    command -v "$cmd" &>/dev/null || fail "required tool not found: $cmd"
done

[[ -f "$VAULT_PASS_FILE" ]] || fail "vault password file not found: $VAULT_PASS_FILE
Create it with:
  printf '%s' 'YOUR_VAULT_PASSWORD' > $VAULT_PASS_FILE
  chmod 600 $VAULT_PASS_FILE"

info "Decrypting ansible vault..."
VAULT_PLAIN=$(ansible-vault decrypt --vault-password-file "$VAULT_PASS_FILE" --output=- "$VAULT_FILE")

vaultkey() {
    local key="$1"
    local val
    val=$(echo "$VAULT_PLAIN" | yq -r ".$key // \"\"")
    if [[ -z "$val" || "$val" == "null" ]]; then
        warn "vault key not found: $key" >&2
        echo "MISSING"
    else
        echo "$val"
    fi
}

info "Extracting credentials from vault..."

mkdir -p "$(dirname "$SECRETS_FILE")"
cat > "$SECRETS_FILE" <<EOF
# nest-mcp credentials — generated by scripts/gen-mcp-secrets.sh
# DO NOT COMMIT. Regenerate after vault rotations: ./scripts/gen-mcp-secrets.sh

# Proxmox (vault: nest_mcp_pve_token — populated by pull-secrets.sh after terraform apply)
NEST_PROXMOX_TOKEN=$(vaultkey "nest_mcp_pve_token")

# VPS / Vultr (vault: vultr_api_key — same value as secrets.tfvars)
NEST_VPS_VULTR_API_KEY=$(vaultkey "vultr_api_key")

# Proxmox Backup Server (vault: pbs_password — same value as secrets.tfvars)
NEST_PBS_PASSWORD=$(vaultkey "pbs_password")

# UniFi (vault: unpoller_unifi_user / unpoller_unifi_pass)
NEST_UNIFI_USERNAME=$(vaultkey "unpoller_unifi_user")
NEST_UNIFI_PASSWORD=$(vaultkey "unpoller_unifi_pass")

# AdGuard Home (vault: adguard_admin_password)
NEST_ADGUARD_PASSWORD=$(vaultkey "adguard_admin_password")

# Home Assistant (vault: homeassistant_bearer_token)
NEST_HA_TOKEN=$(vaultkey "homeassistant_bearer_token")

# Grafana (vault: grafana_admin_password)
NEST_GRAFANA_PASSWORD=$(vaultkey "grafana_admin_password")

# *arr stack (vault: sonarr_api_key / radarr_api_key / etc.)
NEST_SONARR_KEY=$(vaultkey "sonarr_api_key")
NEST_RADARR_KEY=$(vaultkey "radarr_api_key")
NEST_LIDARR_KEY=$(vaultkey "lidarr_api_key")
NEST_PROWLARR_KEY=$(vaultkey "prowlarr_api_key")

# Jellyseerr (vault: jellyseerr_api_key)
NEST_JELLYSEERR_KEY=$(vaultkey "jellyseerr_api_key")

# Jellyfin (vault: jellyfin_api_key — create "nest-mcp" key in Jellyfin dashboard, then run pull-secrets.sh)
NEST_JELLYFIN_KEY=$(vaultkey "jellyfin_api_key")

# MCP HTTP server (serve.py) — only needed on the MCP LXC (192.168.1.19)
MCP_PORT=8765
MCP_AUTHELIA_ISSUER=https://auth.arishaig.site
MCP_CLIENT_ID=nest-mcp
MCP_CLIENT_SECRET=$(vaultkey "authelia_oidc_client_secret_nest_mcp")
EOF
chmod 600 "$SECRETS_FILE"

echo ""
info "Written to $SECRETS_FILE (chmod 600)"

missing=$(grep "=MISSING" "$SECRETS_FILE" | cut -d= -f1 || true)
if [[ -n "$missing" ]]; then
    warn "The following values need attention (run pull-secrets.sh to populate):"
    while IFS= read -r line; do echo "    $line"; done <<< "$missing"
fi
