#!/usr/bin/env bash
# gen-mcp-secrets.sh — Generate ~/.config/nest-mcp/secrets.env from vault + terraform state.
#
# Sources:
#   Ansible vault  → most API keys and passwords
#   terraform output nest_mcp_token  → Proxmox API token (after terraform apply)
#   Existing secrets.env  → preserves NEST_JELLYFIN_KEY (not in vault)
#
# Vault password (in order of precedence):
#   ANSIBLE_VAULT_PASSWORD_FILE  — env var pointing to password file
#   ~/.config/ansible-on-nest/vault-pass  — default location
#
# Usage:
#   ./scripts/gen-mcp-secrets.sh
#   ANSIBLE_VAULT_PASSWORD_FILE=~/.my-vault-pass ./scripts/gen-mcp-secrets.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
VAULT_FILE="$REPO_DIR/inventory/group_vars/all/vault.yml"
TF_DIR="$REPO_DIR/terraform"
SECRETS_FILE="${HOME}/.config/nest-mcp/secrets.env"
VAULT_PASS_FILE="${ANSIBLE_VAULT_PASSWORD_FILE:-$HOME/.config/ansible-on-nest/vault-pass}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
fail()  { echo -e "${RED}[-]${NC} $*" >&2; exit 1; }

# --- Prerequisites ---
for cmd in ansible-vault yq terraform; do
    command -v "$cmd" &>/dev/null || fail "required tool not found: $cmd"
done

[[ -f "$VAULT_PASS_FILE" ]] || fail "vault password file not found: $VAULT_PASS_FILE
Create it with:
  printf '%s' 'YOUR_VAULT_PASSWORD' > $VAULT_PASS_FILE
  chmod 600 $VAULT_PASS_FILE"

# --- Decrypt vault ---
info "Decrypting ansible vault..."
VAULT_PLAIN=$(ansible-vault decrypt --vault-password-file "$VAULT_PASS_FILE" --output=- "$VAULT_FILE")

vaultkey() {
    local key="$1"
    local val
    val=$(echo "$VAULT_PLAIN" | yq -r ".$key // \"\"")
    if [[ -z "$val" || "$val" == "null" ]]; then
        warn "vault key not found: $key"
        echo "MISSING"
    else
        echo "$val"
    fi
}

# --- Read Proxmox token from terraform ---
PROXMOX_TOKEN=""
if [[ -f "$TF_DIR/terraform.tfstate" || -d "$TF_DIR/.terraform" ]]; then
    info "Reading Proxmox token from terraform state..."
    PROXMOX_TOKEN=$(cd "$TF_DIR" && terraform output -raw nest_mcp_token 2>/dev/null || true)
    if [[ -z "$PROXMOX_TOKEN" ]]; then
        warn "terraform output nest_mcp_token is empty — run 'terraform apply' first"
        PROXMOX_TOKEN="MISSING_RUN_TERRAFORM_APPLY"
    fi
else
    warn "No terraform state found — skipping Proxmox token (run terraform apply first)"
    PROXMOX_TOKEN="MISSING_RUN_TERRAFORM_APPLY"
fi

# --- Preserve existing Jellyfin key (not in vault) ---
JELLYFIN_KEY="MISSING_GET_FROM_JELLYFIN_DASHBOARD"
if [[ -f "$SECRETS_FILE" ]]; then
    existing=$(grep "^NEST_JELLYFIN_KEY=" "$SECRETS_FILE" 2>/dev/null | cut -d= -f2- || true)
    if [[ -n "$existing" && "$existing" != "REPLACE" && "$existing" != MISSING* ]]; then
        JELLYFIN_KEY="$existing"
        info "Preserving existing Jellyfin API key from $SECRETS_FILE"
    fi
fi

# --- Extract vault keys ---
info "Extracting credentials from vault..."
ADGUARD_PASSWORD=$(vaultkey "adguard_admin_password")
HA_TOKEN=$(vaultkey "homeassistant_bearer_token")
GRAFANA_PASSWORD=$(vaultkey "grafana_admin_password")
UNIFI_USERNAME=$(vaultkey "unpoller_unifi_user")
UNIFI_PASSWORD=$(vaultkey "unpoller_unifi_pass")
SONARR_KEY=$(vaultkey "sonarr_api_key")
RADARR_KEY=$(vaultkey "radarr_api_key")
LIDARR_KEY=$(vaultkey "lidarr_api_key")
PROWLARR_KEY=$(vaultkey "prowlarr_api_key")
JELLYSEERR_KEY=$(vaultkey "jellyseerr_api_key")

# --- Write secrets file ---
mkdir -p "$(dirname "$SECRETS_FILE")"
cat > "$SECRETS_FILE" <<EOF
# nest-mcp credentials — generated by scripts/gen-mcp-secrets.sh
# DO NOT COMMIT. Regenerate after vault rotations: ./scripts/gen-mcp-secrets.sh

# Proxmox (from: terraform output -raw nest_mcp_token)
NEST_PROXMOX_TOKEN=nest-mcp@pve!nest-mcp=${PROXMOX_TOKEN}

# UniFi (from vault: unpoller_unifi_user / unpoller_unifi_pass)
NEST_UNIFI_USERNAME=${UNIFI_USERNAME}
NEST_UNIFI_PASSWORD=${UNIFI_PASSWORD}

# AdGuard Home (from vault: adguard_admin_password)
NEST_ADGUARD_PASSWORD=${ADGUARD_PASSWORD}

# Home Assistant (from vault: homeassistant_bearer_token)
NEST_HA_TOKEN=${HA_TOKEN}

# Grafana (from vault: grafana_admin_password)
NEST_GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

# *arr stack (from vault: sonarr_api_key / radarr_api_key / etc.)
NEST_SONARR_KEY=${SONARR_KEY}
NEST_RADARR_KEY=${RADARR_KEY}
NEST_LIDARR_KEY=${LIDARR_KEY}
NEST_PROWLARR_KEY=${PROWLARR_KEY}

# Jellyseerr (from vault: jellyseerr_api_key)
NEST_JELLYSEERR_KEY=${JELLYSEERR_KEY}

# Jellyfin — NOT in vault; get from Jellyfin dashboard > Administration > API Keys
NEST_JELLYFIN_KEY=${JELLYFIN_KEY}
EOF
chmod 600 "$SECRETS_FILE"

# --- Report ---
echo ""
info "Written to $SECRETS_FILE (chmod 600)"

missing=$(grep "=MISSING" "$SECRETS_FILE" | cut -d= -f1 || true)
if [[ -n "$missing" ]]; then
    warn "The following values need manual attention:"
    echo "$missing" | sed 's/^/    /'
fi
