#!/usr/bin/env python3
"""Generate architecture diagrams from the ansible-on-nest IaC.

Reads:
  - inventory/hosts.yml       → host groups, IPs
  - terraform/lxc-*.tf        → LXC vmid + description

Outputs (both generated by default):
  - docs/architecture.png       full diagram with monitoring, logs, backups
  - docs/architecture-flow.png  simplified client ingress path only

Setup:
  apt install graphviz
  pip install -r scripts/requirements-diagram.txt
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

try:
    from diagrams import Cluster, Diagram, Edge
    from diagrams.generic.network import VPN
    from diagrams.onprem.compute import Server
    from diagrams.onprem.container import Docker
    from diagrams.onprem.dns import Coredns
    from diagrams.onprem.monitoring import Grafana, Prometheus
    from diagrams.onprem.network import Internet, Traefik
    from diagrams.onprem.storage import Ceph
except ImportError:
    sys.exit("Run: pip install -r scripts/requirements-diagram.txt")

REPO_ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# Solarized Light palette (chrome only — service logos are fixed full-colour PNGs)
# ---------------------------------------------------------------------------

BASE3   = "#fdf6e3"  # canvas background
BASE2   = "#eee8d5"  # outer cluster fill
INNER   = "#e3dcc6"  # nested cluster fill (distinct from BASE2 so they don't muddy)
BASE1   = "#93a1a1"  # cluster borders
BASE00  = "#657b83"  # edges / body text
BASE01  = "#586e75"  # emphasised text (titles, labels)

DIAGRAM_GRAPH = {"bgcolor": BASE3, "fontcolor": BASE01, "fontname": "Sans"}
DIAGRAM_NODE  = {"fontcolor": BASE01, "fontname": "Sans"}
DIAGRAM_EDGE  = {"color": BASE00, "fontcolor": BASE00, "fontname": "Sans"}
CLUSTER       = {"bgcolor": BASE2, "pencolor": BASE1, "fontcolor": BASE01, "fontname": "Sans"}
CLUSTER_INNER = {**CLUSTER, "bgcolor": INNER}


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def parse_inventory(inv_path: Path) -> dict[str, dict]:
    with inv_path.open() as f:
        inv = yaml.safe_load(f)
    hosts: dict[str, dict] = {}
    for group_name, group_data in (inv.get("all", {}).get("children", {}) or {}).items():
        for hostname, host_vars in ((group_data or {}).get("hosts", {}) or {}).items():
            if hostname not in hosts:
                hosts[hostname] = {
                    "group": group_name,
                    "ip": (host_vars or {}).get("ansible_host", ""),
                }
    return hosts


def parse_tf_lxcs(tf_dir: Path) -> dict[str, dict]:
    """Extract vmid + description from proxmox_virtual_environment_container resources."""
    lxcs: dict[str, dict] = {}
    resource_re = re.compile(
        r'resource\s+"proxmox_virtual_environment_container"\s+"(\w+)"'
    )
    for tf_file in sorted(tf_dir.glob("lxc-*.tf")):
        content = tf_file.read_text()
        for m in resource_re.finditer(content):
            name = m.group(1)
            snippet = content[m.end(): m.end() + 600]
            vmid_m = re.search(r'vm_id\s*=\s*(\d+)', snippet)
            desc_m = re.search(r'description\s*=\s*"([^"]+)"', snippet)
            lxcs[name] = {
                "vmid": int(vmid_m.group(1)) if vmid_m else None,
                "description": desc_m.group(1) if desc_m else name,
            }
    return lxcs


# ---------------------------------------------------------------------------
# Label helpers
# ---------------------------------------------------------------------------

def lxc_label(name: str, hosts: dict, lxcs: dict) -> str:
    # "LXC <vmid>: <name>" + IP only. The terraform description is deliberately
    # omitted: it's wider than the single-icon cluster body and overflows the
    # frame, and the icon + node label inside already say what the host does.
    vmid = lxcs.get(name, {}).get("vmid")
    ip   = hosts.get(name, {}).get("ip", "")
    prefix = f"LXC {vmid}: {name}" if vmid else name
    parts = [prefix, ip]
    return "\n".join(p for p in parts if p)


def host_label(name: str, hosts: dict, suffix: str = "") -> str:
    ip = hosts.get(name, {}).get("ip", "")
    parts = [name, ip]
    if suffix:
        parts.append(suffix)
    return "\n".join(p for p in parts if p)


# ---------------------------------------------------------------------------
# Full diagram — all services, monitoring, logs, backups
# ---------------------------------------------------------------------------

def generate_full(hosts: dict, lxcs: dict, out_dir: Path, fmt: str) -> None:
    """Topology view: what runs where. One job — inventory + structural shape.

    The request path lives in the flow diagram; monitoring / logging / backup
    are cross-cutting planes that touch every host, so they're stated once as a
    caption instead of drawn as 30 crossing edges.
    """
    out_file = str(out_dir / "architecture")
    # Caption carries the cross-cutting planes so the graph stays a clean inventory.
    caption = ("ansible-on-nest\n\n"
               "Cross-cutting (not drawn): Prometheus + Loki (monitoring LXC) scrape metrics "
               "and collect Alloy logs from every host · PBS backs up all guests · "
               "Flux reconciles k8s/ from git")
    graph_attr = {**DIAGRAM_GRAPH, "pad": "0.75", "nodesep": "0.60", "ranksep": "0.90",
                  "fontsize": "11", "labelloc": "b"}
    node_attr  = {**DIAGRAM_NODE, "fontsize": "11"}

    with Diagram(
        caption,
        filename=out_file,
        outformat=fmt,
        show=False,
        direction="TB",
        graph_attr=graph_attr,
        node_attr=node_attr,
        edge_attr=DIAGRAM_EDGE,
    ):
        internet = Internet("Internet\n/ Clients")

        with Cluster("Vultr VPS — 66.42.79.175", graph_attr=CLUSTER):
            vps_traefik = Traefik("Traefik\nTCP passthrough :443")
            VPN("WireGuard 10.10.0.1")
            Coredns("AdGuard Home\n(tertiary DNS)")

        with Cluster("Proxmox VE — 192.168.1.16", graph_attr=CLUSTER):

            with Cluster("Talos k8s — alpha 110 · beta 113 · delta 115\n"
                         "Flux GitOps · API VIP .115 · ingress @ .117",
                         graph_attr=CLUSTER_INNER):
                nest_traefik = Traefik("k8s Traefik\n+ Authelia")
                Docker("app-template\nHelmReleases\n(Sonarr · Radarr\nJellyfin…)")

            with Cluster(lxc_label("monitoring", hosts, lxcs), graph_attr=CLUSTER):
                Prometheus("Prometheus")
                Grafana("Grafana")
                Server("Loki + Ruler")

            with Cluster(lxc_label("fileserver", hosts, lxcs), graph_attr=CLUSTER):
                Ceph("Samba / NFS\n/Tank/media_root")

            with Cluster(lxc_label("seedbox", hosts, lxcs), graph_attr=CLUSTER):
                Server("qBittorrent\n+ Gluetun VPN")

            with Cluster(lxc_label("musicbrainz", hosts, lxcs), graph_attr=CLUSTER):
                Server("MusicBrainz")

            with Cluster(lxc_label("scrutiny", hosts, lxcs), graph_attr=CLUSTER):
                Server("Scrutiny\n(SMART)")

            with Cluster(lxc_label("dns-secondary", hosts, lxcs), graph_attr=CLUSTER):
                adguard2 = Coredns("AdGuard Home\n(secondary) + Unbound")

            with Cluster(lxc_label("mcp", hosts, lxcs), graph_attr=CLUSTER):
                Server("nest-mcp :8765")

            with Cluster(lxc_label("ci", hosts, lxcs), graph_attr=CLUSTER):
                Server("Actions runner\n(deploy)")

            with Cluster(lxc_label("foundry", hosts, lxcs), graph_attr=CLUSTER):
                Server("FoundryVTT")

            with Cluster(lxc_label("docker", hosts, lxcs), graph_attr=CLUSTER):
                Docker("decommissioned\n(scratch host)")

            with Cluster("VM 107: homeassistant\n192.168.4.50 (VLAN 4)", graph_attr=CLUSTER):
                Server("Home Assistant OS")

            with Cluster("VM 500: backup\n192.168.1.113", graph_attr=CLUSTER):
                Server("Proxmox Backup Server")

        with Cluster(host_label("adguard", hosts, "(primary DNS)"), graph_attr=CLUSTER):
            adguard = Coredns("AdGuard Home\n+ Unbound")

        # Only the structural edges a reader can't infer from the boxes alone.
        internet     >> Edge(label="HTTPS") >> vps_traefik
        vps_traefik  >> Edge(label="WireGuard tunnel", style="dashed") >> nest_traefik
        internet     >> Edge(label="DNS", style="dotted") >> adguard
        adguard      >> Edge(label="failover", style="dashed") >> adguard2

    print(f"Written: {out_file}.{fmt}")


# ---------------------------------------------------------------------------
# Flow diagram — client ingress path only
# ---------------------------------------------------------------------------

def generate_flow(hosts: dict, lxcs: dict, out_dir: Path, fmt: str) -> None:
    out_file = str(out_dir / "architecture-flow")
    graph_attr = {**DIAGRAM_GRAPH, "pad": "0.80", "splines": "ortho",
                  "nodesep": "0.80", "ranksep": "1.10", "labelloc": "b"}
    node_attr  = {**DIAGRAM_NODE, "fontsize": "13"}

    with Diagram(
        "ansible-on-nest — Client Flow",
        filename=out_file,
        outformat=fmt,
        show=False,
        direction="LR",
        graph_attr=graph_attr,
        node_attr=node_attr,
        edge_attr=DIAGRAM_EDGE,
    ):
        client = Internet("Client")

        with Cluster("Vultr VPS\n66.42.79.175", graph_attr=CLUSTER):
            vps_traefik = Traefik("Traefik\nTCP passthrough\n:443")
            vps_wg      = VPN("WireGuard\n10.10.0.1")

        with Cluster("Talos k8s cluster\nFlux GitOps", graph_attr=CLUSTER):
            nest_wg        = VPN("WireGuard\n10.10.0.3 (alpha)")
            nest_traefik   = Traefik("k8s Traefik\nMetalLB 192.168.1.117\nTLS term · PROXY v2")
            authelia       = Server("Authelia\nSSO / 2FA")
            svc_protected  = Docker("Protected services\n(Sonarr · Radarr · Grafana…)")
            svc_local      = Docker("LAN-only services\n(Tunarr · Watcharr)")
            svc_open       = Docker("Open services\n(Jellyfin · Seerr)")

        with Cluster(host_label("adguard", hosts, "(primary DNS)"), graph_attr=CLUSTER):
            adguard = Coredns("AdGuard Home\n+ Unbound")

        client      >> Edge(label="HTTPS") >> vps_traefik
        vps_traefik >> Edge(label="TCP passthrough") >> vps_wg
        vps_wg      >> Edge(label="WireGuard tunnel", style="dashed") >> nest_wg
        nest_wg     >> nest_traefik

        nest_traefik >> authelia
        authelia     >> Edge(label="authorized") >> svc_protected
        nest_traefik >> Edge(label="local-only") >> svc_local
        nest_traefik >> Edge(label="no auth") >> svc_open

        client >> Edge(label="DNS", style="dotted") >> adguard

    print(f"Written: {out_file}.{fmt}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        default=str(REPO_ROOT / "docs"),
        help="Output directory (default: docs/)",
    )
    parser.add_argument(
        "--format",
        default="png",
        choices=["png", "svg", "pdf"],
        dest="fmt",
    )
    parser.add_argument(
        "--mode",
        default="both",
        choices=["both", "full", "flow"],
        help="Which diagram(s) to generate (default: both)",
    )
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(exist_ok=True)

    hosts = parse_inventory(REPO_ROOT / "inventory" / "hosts.yml")
    lxcs  = parse_tf_lxcs(REPO_ROOT / "terraform")

    if args.mode in ("both", "full"):
        generate_full(hosts, lxcs, out_dir, args.fmt)
    if args.mode in ("both", "flow"):
        generate_flow(hosts, lxcs, out_dir, args.fmt)


if __name__ == "__main__":
    main()
