#!/usr/bin/env python3
"""Generate architecture diagrams from the ansible-on-nest IaC.

Reads:
  - inventory/hosts.yml       → host groups, IPs
  - terraform/lxc-*.tf        → LXC vmid + description

Outputs (both generated by default):
  - docs/architecture.png       full diagram with monitoring, logs, backups
  - docs/architecture-flow.png  simplified client ingress path only

Setup:
  apt install graphviz
  pip install -r scripts/requirements-diagram.txt
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

try:
    from diagrams import Cluster, Diagram, Edge
    from diagrams.generic.network import VPN
    from diagrams.onprem.compute import Server
    from diagrams.onprem.container import Docker
    from diagrams.onprem.dns import Coredns
    from diagrams.onprem.monitoring import Grafana, Prometheus
    from diagrams.onprem.network import Internet, Traefik
    from diagrams.onprem.storage import Ceph
except ImportError:
    sys.exit("Run: pip install -r scripts/requirements-diagram.txt")

REPO_ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def parse_inventory(inv_path: Path) -> dict[str, dict]:
    with inv_path.open() as f:
        inv = yaml.safe_load(f)
    hosts: dict[str, dict] = {}
    for group_name, group_data in (inv.get("all", {}).get("children", {}) or {}).items():
        for hostname, host_vars in ((group_data or {}).get("hosts", {}) or {}).items():
            if hostname not in hosts:
                hosts[hostname] = {
                    "group": group_name,
                    "ip": (host_vars or {}).get("ansible_host", ""),
                }
    return hosts


def parse_tf_lxcs(tf_dir: Path) -> dict[str, dict]:
    """Extract vmid + description from proxmox_virtual_environment_container resources."""
    lxcs: dict[str, dict] = {}
    resource_re = re.compile(
        r'resource\s+"proxmox_virtual_environment_container"\s+"(\w+)"'
    )
    for tf_file in sorted(tf_dir.glob("lxc-*.tf")):
        content = tf_file.read_text()
        for m in resource_re.finditer(content):
            name = m.group(1)
            snippet = content[m.end(): m.end() + 600]
            vmid_m = re.search(r'vm_id\s*=\s*(\d+)', snippet)
            desc_m = re.search(r'description\s*=\s*"([^"]+)"', snippet)
            lxcs[name] = {
                "vmid": int(vmid_m.group(1)) if vmid_m else None,
                "description": desc_m.group(1) if desc_m else name,
            }
    return lxcs


# ---------------------------------------------------------------------------
# Label helpers
# ---------------------------------------------------------------------------

def lxc_label(name: str, hosts: dict, lxcs: dict) -> str:
    vmid = lxcs.get(name, {}).get("vmid")
    ip   = hosts.get(name, {}).get("ip", "")
    desc = lxcs.get(name, {}).get("description", "")
    prefix = f"LXC {vmid}: {name}" if vmid else name
    parts = [prefix, ip]
    if desc:
        parts.append(f"({desc})")
    return "\n".join(p for p in parts if p)


def host_label(name: str, hosts: dict, suffix: str = "") -> str:
    ip = hosts.get(name, {}).get("ip", "")
    parts = [name, ip]
    if suffix:
        parts.append(suffix)
    return "\n".join(p for p in parts if p)


# ---------------------------------------------------------------------------
# Full diagram — all services, monitoring, logs, backups
# ---------------------------------------------------------------------------

def generate_full(hosts: dict, lxcs: dict, out_dir: Path, fmt: str) -> None:
    out_file = str(out_dir / "architecture")
    graph_attr = {"pad": "0.75", "splines": "ortho", "nodesep": "0.60", "ranksep": "0.90"}
    node_attr  = {"fontsize": "11"}

    with Diagram(
        "ansible-on-nest",
        filename=out_file,
        outformat=fmt,
        show=False,
        direction="TB",
        graph_attr=graph_attr,
        node_attr=node_attr,
    ):
        internet = Internet("Internet\n/ Clients")

        with Cluster("Vultr VPS — 66.42.79.175"):
            vps_traefik = Traefik("Traefik\n:80 / :443")
            vps_wg      = VPN("WireGuard\n10.10.0.1")
            vps_obs     = Server("node_exporter\n+ Alloy")

        with Cluster("Proxmox VE — 192.168.1.16"):

            with Cluster(lxc_label("docker", hosts, lxcs)):
                nest_traefik = Traefik("Traefik")
                nest_docker  = Docker("Docker services\n(Sonarr · Radarr · Jellyfin…)")
                nest_wg      = VPN("WireGuard\n10.10.0.2")

            with Cluster(lxc_label("monitoring", hosts, lxcs)):
                prom = Prometheus("Prometheus")
                graf = Grafana("Grafana")
                lok  = Server("Loki + Ruler\n(Alertmanager)")

            with Cluster(lxc_label("fileserver", hosts, lxcs)):
                files = Ceph("Samba")

            with Cluster(lxc_label("scrutiny", hosts, lxcs)):
                scrut = Server("Scrutiny\n(SMART)")

            with Cluster(lxc_label("seedbox", hosts, lxcs)):
                seed = Server("qBittorrent\n+ Gluetun VPN")

            with Cluster(lxc_label("musicbrainz", hosts, lxcs)):
                mb = Server("MusicBrainz")

            with Cluster(lxc_label("dns-secondary", hosts, lxcs)):
                adguard2 = Coredns("AdGuard Home\n(secondary)")
                unbound2 = Server("Unbound")

            with Cluster(lxc_label("mcp", hosts, lxcs)):
                mcp = Server("nest-mcp\n:8765")

            with Cluster(lxc_label("ci", hosts, lxcs)):
                ci = Server("GitHub Actions\nrunner")

            with Cluster("VM 107: homeassistant\n192.168.4.50 (VLAN 4)"):
                ha = Server("Home Assistant OS")

            with Cluster("VM 500: backup\n192.168.1.113"):
                pbs = Server("Proxmox\nBackup Server")

        with Cluster(host_label("adguard", hosts, "(primary DNS)")):
            adguard = Coredns("AdGuard Home")
            unbound = Server("Unbound")

        # Ingress path
        internet >> vps_traefik >> vps_wg
        vps_wg   >> Edge(label="WireGuard tunnel", style="dashed") >> nest_wg
        nest_wg  >> nest_traefik >> nest_docker

        # DNS
        adguard  >> Edge(label="upstream") >> unbound
        adguard2 >> Edge(label="upstream") >> unbound2
        adguard  >> Edge(label="failover", style="dashed") >> adguard2

        # Monitoring — metrics
        lxc_targets = [nest_docker, files, scrut, seed, mb, ha, pbs, mcp, ci]
        prom >> Edge(label="scrape") >> lxc_targets
        prom >> Edge(label="scrape\n(WireGuard)", style="dashed") >> vps_obs
        graf - [prom, lok]

        # Log shipping — Alloy on every host ships to Loki
        all_log_sources = [nest_docker, seed, scrut, mb, files, mcp, pbs, ci]
        all_log_sources >> Edge(label="logs (Alloy)", color="blue") >> lok
        vps_obs >> Edge(label="logs (Alloy)\n(WireGuard)", style="dashed", color="blue") >> lok

        # Backups
        [nest_docker, files, scrut, seed, mb, ha] >> Edge(label="backup") >> pbs

        # DNS (representative)
        nest_docker >> Edge(label="DNS", style="dotted", color="gray") >> adguard

    print(f"Written: {out_file}.{fmt}")


# ---------------------------------------------------------------------------
# Flow diagram — client ingress path only
# ---------------------------------------------------------------------------

def generate_flow(hosts: dict, lxcs: dict, out_dir: Path, fmt: str) -> None:
    out_file = str(out_dir / "architecture-flow")
    graph_attr = {"pad": "0.80", "splines": "ortho", "nodesep": "0.80", "ranksep": "1.10"}
    node_attr  = {"fontsize": "13"}

    with Diagram(
        "ansible-on-nest — Client Flow",
        filename=out_file,
        outformat=fmt,
        show=False,
        direction="LR",
        graph_attr=graph_attr,
        node_attr=node_attr,
    ):
        client = Internet("Client")

        with Cluster("Vultr VPS\n66.42.79.175"):
            vps_traefik = Traefik("Traefik\nTCP passthrough\n:443")
            vps_wg      = VPN("WireGuard\n10.10.0.1")

        with Cluster(lxc_label("docker", hosts, lxcs)):
            nest_wg        = VPN("WireGuard\n10.10.0.2")
            nest_traefik   = Traefik("Traefik\nTLS termination\nPROXY protocol v2")
            authelia       = Server("Authelia\nSSO / 2FA")
            svc_protected  = Docker("Protected services\n(Sonarr · Radarr · Grafana…)")
            svc_local      = Docker("LAN-only services\n(Tunarr · Watcharr)")
            svc_open       = Docker("Open services\n(Jellyfin · Seerr)")

        with Cluster(host_label("adguard", hosts, "(primary DNS)")):
            adguard = Coredns("AdGuard Home\n+ Unbound")

        client      >> Edge(label="HTTPS") >> vps_traefik
        vps_traefik >> Edge(label="TCP passthrough") >> vps_wg
        vps_wg      >> Edge(label="WireGuard tunnel", style="dashed") >> nest_wg
        nest_wg     >> nest_traefik

        nest_traefik >> authelia
        authelia     >> Edge(label="authorized") >> svc_protected
        nest_traefik >> Edge(label="local-only") >> svc_local
        nest_traefik >> Edge(label="no auth") >> svc_open

        client >> Edge(label="DNS", style="dotted", color="gray") >> adguard

    print(f"Written: {out_file}.{fmt}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        default=str(REPO_ROOT / "docs"),
        help="Output directory (default: docs/)",
    )
    parser.add_argument(
        "--format",
        default="png",
        choices=["png", "svg", "pdf"],
        dest="fmt",
    )
    parser.add_argument(
        "--mode",
        default="both",
        choices=["both", "full", "flow"],
        help="Which diagram(s) to generate (default: both)",
    )
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(exist_ok=True)

    hosts = parse_inventory(REPO_ROOT / "inventory" / "hosts.yml")
    lxcs  = parse_tf_lxcs(REPO_ROOT / "terraform")

    if args.mode in ("both", "full"):
        generate_full(hosts, lxcs, out_dir, args.fmt)
    if args.mode in ("both", "flow"):
        generate_flow(hosts, lxcs, out_dir, args.fmt)


if __name__ == "__main__":
    main()
