#!/usr/bin/env bash
# render-k8s-secrets.sh — Generate the SOPS-encrypted k8s Secrets that Flux
# reconciles, from playbooks/provision/k8s-secrets.yml (docs/secrets.md).
#
#   ./scripts/render-k8s-secrets.sh          write/update k8s/**/<name>.sops.yaml
#   ./scripts/render-k8s-secrets.sh --check  change nothing; exit 1 if any file
#                                            is missing, stale or orphaned
#
# Values are rendered through Ansible, so vars from group_vars/all.sops.yaml
# and template lookups resolve exactly as they did in k8s.yml. SOPS ciphertext
# differs on every encrypt, so a file is rewritten only when its decrypted
# content would change; otherwise git sees no diff.
#
# Needs: ansible (with community.sops), sops, the age key (docs/secrets.md).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
MODE="${1:-write}"
case $MODE in write|--check) ;; *) echo "usage: $0 [--check]" >&2; exit 2;; esac

cd "$REPO_DIR"
TMP=$(mktemp -d)
chmod 700 "$TMP"
trap 'rm -rf "$TMP"' EXIT

ansible-playbook playbooks/provision/k8s-secrets.yml -e "render_out=$TMP/rendered.json" \
    </dev/null >"$TMP/ansible.log" 2>&1 \
    || { echo "rendering failed:" >&2; tail -20 "$TMP/ansible.log" >&2; exit 1; }

python3 - "$TMP/rendered.json" "$MODE" <<'PY'
import glob, json, os, subprocess, sys, yaml

rendered, mode = sys.argv[1], sys.argv[2]
check = mode == "--check"

# Namespace -> directory whose kustomization.yaml lists the file.
DIRS = {
    "media": "k8s/apps/media",
    "nest-mcp": "k8s/apps/nest-mcp",
    "authelia": "k8s/infrastructure/authelia",
    "cert-manager": "k8s/infrastructure/cert-manager",
}
NOTE = "  # SOPS-encrypted; generated by scripts/render-k8s-secrets.sh"


def manifest(e):
    kind = e.get("kind", "Secret")
    m = {"apiVersion": "v1", "kind": kind,
         "metadata": {"name": e["name"], "namespace": e["namespace"]}}
    data = {k: str(v) for k, v in (e.get("data") or {}).items()}
    if kind == "Secret":
        m["type"] = "Opaque"
        m["stringData"] = data
    else:
        m["data"] = data
    return m


def decrypt(path):
    r = subprocess.run(["sops", "decrypt", path], capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"cannot decrypt {path}: {r.stderr.strip()}")
    return yaml.safe_load(r.stdout)


def encrypt(path, m):
    plain = yaml.safe_dump(m, sort_keys=False, default_flow_style=False, width=1 << 30)
    r = subprocess.run(
        ["sops", "encrypt", "--filename-override", path,
         "--input-type", "yaml", "--output-type", "yaml", "/dev/stdin"],
        input=plain, capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"cannot encrypt {path}: {r.stderr.strip()}")
    with open(path, "w") as f:
        f.write(r.stdout)


def listed(kpath, fname):
    return any(l.strip().split("#")[0].strip() == f"- {fname}" for l in open(kpath))


def add_to_kustomization(kpath, fname):
    lines = open(kpath).read().split("\n")
    start = next(i for i, l in enumerate(lines) if l.rstrip() == "resources:")
    last = start
    for i in range(start + 1, len(lines)):
        l = lines[i]
        if l and not l.startswith((" ", "#")):
            break  # next top-level key
        if l.startswith("  - "):
            last = i
    lines.insert(last + 1, f"  - {fname}{NOTE}")
    open(kpath, "w").write("\n".join(lines))


entries = json.load(open(rendered))
problems, written, unchanged = [], [], 0
wanted = set()
for e in entries:
    ns = e["namespace"]
    if ns not in DIRS:
        sys.exit(f"{e['name']}: no directory mapped for namespace {ns}")
    d = DIRS[ns]
    fname = f"{e['name']}.sops.yaml"
    path = f"{d}/{fname}"
    wanted.add(path)
    m = manifest(e)
    current = decrypt(path) if os.path.exists(path) else None
    if current is not None:
        current.pop("sops", None)
    if current == m:
        unchanged += 1
    elif check:
        problems.append(f"{path}: {'missing' if current is None else 'stale'}")
    else:
        encrypt(path, m)
        written.append(path)
    kpath = f"{d}/kustomization.yaml"
    if not listed(kpath, fname):
        if check:
            problems.append(f"{kpath}: does not list {fname}")
        else:
            add_to_kustomization(kpath, fname)
            written.append(kpath)

# Every *.sops.yaml under k8s/ is generated, so one not in the spec is orphaned.
for path in sorted(glob.glob("k8s/**/*.sops.yaml", recursive=True)):
    if path not in wanted:
        problems.append(f"{path}: not in playbooks/provision/k8s-secrets.yml (orphan)")

print(f"{len(entries)} entries: {unchanged} unchanged, {len(written)} files written")
for w in written:
    print(f"  wrote {w}")
if problems:
    print("PROBLEMS:" if check else "WARNINGS:")
    for p in problems:
        print(f"  {p}")
    if check:
        print("Run ./scripts/render-k8s-secrets.sh and commit the result.")
    sys.exit(1)
PY
