apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nest-mcp
  namespace: nest-mcp
spec:
  entryPoints: [websecure]
  routes:
    - match: "Host(`mcp.arishaig.site`)"
      kind: Rule
      services:
        - name: nest-mcp
          port: 8765
  tls: {}
